# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    groups:
      all:
        patterns:
        - "*"
    commit-message:
      prefix: "ci(deps):"

  - package-ecosystem: uv
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: weekly
    groups:
      all:
        patterns:
        - "*"
    commit-message:
      prefix: "chore(deps):"