#! /usr/bin/env bash

SUBPACKAGE_DIRS=(
    "core"
    "mosaic"
    "application"
    "meta"
)

for PACKAGE_DIR in "${SUBPACKAGE_DIRS[@]}"
do
    echo "publishing titiler-${PACKAGE_DIR}"
    pushd ./src/titiler/${PACKAGE_DIR}
    rm -rf dist
    flit build
    popd
done
