#! /usr/bin/env bash

SUBPACKAGE_DIRS=(
    "core"
    "mosaic"
    "application"
    "extensions"
)

for PACKAGE_DIR in "${SUBPACKAGE_DIRS[@]}"
do
    echo "publishing titiler-${PACKAGE_DIR}"
    pushd ./src/titiler/${PACKAGE_DIR}
    rm -rf dist
    python -m build
    twine upload dist/*
    popd
done

rm -rf dist
python -m build
twine upload dist/*
