#! /usr/bin/env bash

SUBPACKAGES=(
    "core"
    "xarray"
    "mosaic"
    "application"
    "extensions"
)

for PACKAGE in "${SUBPACKAGES[@]}"
do
    echo "publishing titiler-${PACKAGE}"
    rm -rf dist
    uv build --package titiler-${PACKAGE}
    uv publish
done
