#! /usr/bin/env bash

SUBMODULES=(
    "core"
    "xarray"
    "mosaic"
    "application"
    "extensions"
)

for SUBMODULE in "${SUBMODULES[@]}"
do
    echo "Running tests for titiler-${SUBMODULE}"
    uv run pytest src/titiler/${SUBMODULE} --cov=titiler.${SUBMODULE} --cov-report=xml:titiler-${SUBMODULE}.xml  --cov-report=term-missing
done
