name: Deploy application

on:
  workflow_call:
    secrets:
      AWS_IAM_ROLE_ARN:
        required: true
      STACK_NAME:
        required: true
      STACK_STAGE:
        required: true
      STACK_MEMORY:
        required: true
      STACK_OWNER:
        required: true
      STACK_CLIENT:
        required: true
      STACK_BUCKETS:
        required: true
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment
    if: github.repository == 'developmentseed/titiler'
    defaults:
      run:
        working-directory: deployment/aws
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      # Let's wait a bit to make sure Pypi is up to date
      - name: Sleep for 120 seconds
        run: sleep 120s
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: us-east-1

      - name: Set up uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          enable-cache: false

      - name: Install dependencies
        run: uv sync --all-packages && npm install -g aws-cdk@^2.232.2

      # Let's wait a bit to make sure package is available on pypi
      - name: Sleep for 120 seconds
        run: sleep 120s
        shell: bash

      # Build and Deploy CDK application
      - name: Build & Deploy
        run: uv run cdk deploy ${{ secrets.STACK_NAME }}-lambda-${{ secrets.STACK_STAGE }} --require-approval never
        env:
          TITILER_STACK_NAME: ${{ secrets.STACK_NAME }}
          TITILER_STACK_STAGE: ${{ secrets.STACK_STAGE }}
          TITILER_STACK_MEMORY: ${{ secrets.STACK_MEMORY }}
          TITILER_STACK_OWNER: ${{ secrets.STACK_OWNER }}
          TITILER_STACK_CLIENT: ${{ secrets.STACK_CLIENT }}
          TITILER_STACK_BUCKETS: ${{ secrets.STACK_BUCKETS }}
